server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
#      uri:  mongodb://root:root@192.168.1.148:27017
      uri:  mongodb://root:root@192.168.8.36:27017
      database: xc_cms